# Generated by Django 5.1 on 2024-08-28 13:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fatura', models.CharField(default=uuid.uuid4, max_length=50)),
                ('descricao', models.TextField(blank=True, max_length=200)),
                ('foto', models.ImageField(blank=True, upload_to='devis/foto/')),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('disponibilidade', models.CharField(max_length=1000)),
                ('endereco', models.CharField(blank=True, max_length=20)),
                ('codpostal', models.CharField(blank=True, max_length=20)),
                ('vila', models.CharField(blank=True, max_length=20)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.servico')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='devis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
            },
        ),
    ]
